name: CI
on:
  pull_request:
  push:
    branches: [main]

env:
  app: frontend/
  sw: packages/transpilation/
  tests: tests/

jobs:

##############################################################

  tests:
    name: Tests
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        # browsers: [chrome, firefox, safari, edge]
        ci_browser:
        - Chrome
        - Firefox

    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - name: Environment Info
      run: |
        firefox --version
        google-chrome --version
        echo "Node: $( node --version )"
        echo "NPM: $( npm --version )"
        echo "Yarn: $( yarn --version )"

    - run: yarn install

    - name: Test
      run: yarn test:ember
      working-directory: ${{ env.app }}
      env:
        CI_BROWSER: ${{ matrix.ci_browser }}

##############################################################

  build_app:
    name: Build App
    runs-on: ubuntu-latest
    timeout-minutes: 10

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install
    - name: 'Build'
      run: yarn predeploy
    - name: Copy deploy host config
      run: cp ./config/netlify/_redirects ./dist/
      working-directory: ${{ env.app }}

    - name: Upload App Artifacts
      uses: actions/upload-artifact@v2
      with:
        name: built_app
        path: ${{ env.app }}/dist/

##############################################################

  cypress:
    name: Cypress Tests
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build_app]

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install
    - run: yarn browserstack-cypress run --sync
      working-directory: ${{ env.tests }}

##############################################################

  deploy:
    name: Deploy to Netlify
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build_app]

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - name: Download Built App Artifacts
      uses: actions/download-artifact@master
      with:
        name: built_app
        path: ${{ env.app }}/deploy/app/

    - name: Deploy to Netlify
      env:
        NETLIFY_ACCESS_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
        NETLIFY_CLI_VERSION: 0.4.0
      run: |
        cp ./config/netlify/_redirects ./deploy/app

        wget https://github.com/netlify/netlifyctl/releases/download/v$NETLIFY_CLI_VERSION/netlifyctl-linux-amd64-$NETLIFY_CLI_VERSION.tar.gz
        tar -xf netlifyctl-linux-amd64-$NETLIFY_CLI_VERSION.tar.gz

        ./netlifyctl -y deploy --site-id $NETLIFY_SITE_ID --access-token $NETLIFY_ACCESS_TOKEN --publish-directory "./deploy/app"
      working-directory: ${{ env.app }}


##############################################################

  deploy_preview:
    name: Deploy Preview
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [build_app]

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1

    - name: Download Built App Artifacts
      uses: actions/download-artifact@master
      with:
        name: built_app
        path: ${{ env.app }}/deploy/app/

    - name: Deploy to Netlify
      id: deploy
      uses: nwtgck/actions-netlify@v1.2.2
      with:
        publish-dir: '${{ env.app }}/deploy/app'
        production-branch: __handled_separately__
        github-token: ${{ secrets.GITHUB_TOKEN }}
      env:
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_ACCESS_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}

