name: CI
on:
  pull_request:
  push:
    branches: [main, preview-embroider-upgrade]

##############################################################

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  codemirror: packages/codemirror/
  consts: packages/consts/
  horizon: packages/horizon-theme/
  monaco: packages/monaco
  sw: packages/transpilation/
  NODE_OPTIONS: "--max-old-space-size=4096 --trace-warnings --unhandled-rejections=strict"
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

permissions:
  contents: read

##############################################################

jobs:

##############################################################

  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: TurboRepo local server
      uses: felixmosh/turborepo-gh-artifacts@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
    - run:  echo ${{ github.event.number }} > ./pr-number.txt
    - run: pnpm turbo build
    - uses: actions/upload-artifact@v3
      with:
        name: pr-number 
        path: pr-number.txt
    # not needed since we use turbo 
    # - uses: actions/upload-artifact@v3
    #   with:
    #     name: dists-${{ github.event.number }} 
    #     path: |
    #       ./**/dist/
    #       !node_modules/
    #       !**/node_modules/
    #     if-no-files-found: error

##############################################################

  lints:
    name: "Lints"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v3
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - run: pnpm lint

##############################################################

  tests:
    name: Tests
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        # browsers: [chrome, firefox, safari, edge]
        ci_browser:
        - Chrome
        - Firefox

    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [install_dependencies]

    steps:
    - uses: actions/checkout@v3
    - name: TurboRepo local server
      uses: felixmosh/turborepo-gh-artifacts@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
    - name: Environment Info
      run: |
        firefox --version
        google-chrome --version
        echo "Node: $( node --version )"
        echo "NPM: $( npm --version )"
        echo "pnpm: $( pnpm --version )"
    - name: Test
      run: pnpm turbo test:ember --output-logs errors-only
      env:
        CI_BROWSER: ${{ matrix.ci_browser }}

  try-scenarios:
    name: "Test try-scenarios" 
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [tests]
    steps:
    - uses: actions/checkout@v3
    - name: TurboRepo local server
      uses: felixmosh/turborepo-gh-artifacts@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
    - name: Test
      run: pnpm turbo test:scenarios


