name: CI
on:
  pull_request:
  push:
    branches: [main, preview-embroider-upgrade]

##############################################################

concurrency: ${{ github.workflow }}-${{ github.ref }}

env:
  codemirror: packages/codemirror/
  consts: packages/consts/
  horizon: packages/horizon-theme/
  monaco: packages/monaco
  sw: packages/transpilation/
  NODE_OPTIONS: "--max-old-space-size=4096 --trace-warnings --unhandled-rejections=strict"
  TURBO_API: http://127.0.0.1:9080
  TURBO_TOKEN: this-is-not-a-secret
  TURBO_TEAM: myself

permissions:
  contents: read

##############################################################

jobs:

##############################################################

  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 15

    steps:
    - uses: actions/checkout@v3
    - name: TurboRepo local server
      uses: felixmosh/turborepo-gh-artifacts@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0

##############################################################

  lints:
    name: "Lints"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v3
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - run: pnpm lint

##############################################################

  tests:
    name: Tests
    strategy:
      matrix:
        # os: [ubuntu-latest, macOS-latest, windows-latest]
        # browsers: [chrome, firefox, safari, edge]
        ci_browser:
        - Chrome
        - Firefox

    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [install_dependencies]

    steps:
    - uses: actions/checkout@v3
    - name: TurboRepo local server
      uses: felixmosh/turborepo-gh-artifacts@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
    - name: Environment Info
      run: |
        firefox --version
        google-chrome --version
        echo "Node: $( node --version )"
        echo "NPM: $( npm --version )"
        echo "pnpm: $( pnpm --version )"
    - name: Test
      run: pnpm turbo test:ember
      env:
        CI_BROWSER: ${{ matrix.ci_browser }}

  try-scenarios:
    name: "Test try-scenarios" 
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [tests]
    steps:
    - uses: actions/checkout@v3
    - name: TurboRepo local server
      uses: felixmosh/turborepo-gh-artifacts@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
    - name: Test
      run: pnpm turbo test:scenarios


  browserstack-test:
    name: Browserstack Tests (Safari, Edge, etc)
    runs-on: ubuntu-latest
    timeout-minutes: 20
    needs: [tests]

    env:
      BROWSERSTACK_ACCESS_KEY: ${{ secrets.BROWSERSTACK_ACCESS_KEY }}
      BROWSERSTACK_USERNAME: ${{ secrets.BROWSERSTACK_USERNAME }}

    steps:
    - uses: actions/checkout@v3
    - name: TurboRepo local server
      uses: felixmosh/turborepo-gh-artifacts@v2
      with:
        repo-token: ${{ secrets.GITHUB_TOKEN }}
    - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
    - run: pnpm turbo test:browserstack

##############################################################
##############################################################


  DeployPreview:
    name: "Deploy: Preview"
    if: github.ref != 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [install_dependencies]
    permissions:
      contents: read
      deployments: write
    outputs:
      limberUrl: ${{ steps.publishLimber.outputs.url }}
      tutorialUrl: ${{ steps.publishTutorial.outputs.url }}
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - run: pnpm turbo build 
      - name: Publish Limber 
        id: publishLimber
        uses: cloudflare/pages-action@v1.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: limber-glimdown
          directory: ./apps/repl/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Tutorial 
        id: publishTutorial
        uses: cloudflare/pages-action@v1.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: limber-glimmer-tutorial
          directory: ./apps/tutorial/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}

  DeployProduction:
    name: "Deploy: Production"
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest
    timeout-minutes: 15
    needs: [browserstack-test]
    permissions:
      contents: read
      deployments: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - run: pnpm turbo build 
      - name: Publish Limber 
        uses: cloudflare/pages-action@v1.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: limber-glimdown
          directory: ./apps/repl/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}
      - name: Publish Tutorial 
        uses: cloudflare/pages-action@v1.4.1
        with:
          apiToken: ${{ secrets.CLOUDFLARE_API_TOKEN }}
          accountId: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
          projectName: limber-glimmer-tutorial
          directory: ./apps/tutorial/dist
          gitHubToken: ${{ secrets.GITHUB_TOKEN }}


  PostComment:
    name: Post Preview URL as comment to PR
    runs-on: ubuntu-latest
    needs: [DeployPreview]
    if: github.ref != 'refs/heads/main'
    permissions:
      pull-requests: write
    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - uses: marocchino/sticky-pull-request-comment@v2
        with:
          header: preview-urls 
          message: |+
            | Project   | Preview URL |
            | -------   | ----------- |
            | Limber    | ${{ needs.DeployPreview.outputs.limberUrl }}   |
            | Tutorial  | ${{ needs.DeployPreview.outputs.tutorialUrl }} |



  # https://github.com/changesets/action
  release:
    name: Release
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
    needs: [browserstack-test, try-scenarios]

    steps:
      - uses: actions/checkout@v3
        with:
          persist-credentials: false
      - name: TurboRepo local server
        uses: felixmosh/turborepo-gh-artifacts@v2
        with:
          repo-token: ${{ secrets.GITHUB_TOKEN }}
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - name: Create Release Pull Request or Publish to npm
        id: changesets
        uses: changesets/action@v1
        with:
          # This expects you to have a script called release which does a build for your packages and calls changeset publish
          publish: pnpm release
          title: "Release Preview"
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}



