name: "Lints'n'Stuff"
on:
  pull_request:
    branches: [main]

env:
  app: limber/
  sw: transpilation-worker/

jobs:
  js:
    name: "JS/TS"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - name: 'Limber App'
      working-directory: ${{ env.app }}
      run: npm run lint:js
    - name: 'Worker'
      working-directory: ${{ env.sw }}
      run: npm run lint:js

  templates:
    name: "Templates"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run lint:hbs
      working-directory: ${{ env.app }}

    # - name: "Styles"
    #   run: yarn stylelint ${{ env.app }}/**/*.css

    # - name: "Translations"
    #   run: yarn lint:i18n
    #   continue-on-error: true

  types:
    name: "Type Correctness"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install
    - run: npm run check:types
      working-directory: ${{ env.app }}

