name: "Lints'n'Stuff"
on:
  pull_request:
    branches: [main]

env:
  app: frontend/
  # packages
  codemirror: packages/codemirror/
  consts: packages/consts/
  horizon: packages/horizon-theme/
  tests: tests/
  sw: packages/transpilation/

jobs:
  install_dependencies:
    name: Install Dependencies
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm

  lints:
    name: "Lints"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v2
      - uses: ./.github/actions/pnpm
      - run: pnpm --filter '*' lint

  types:
    name: "Type Correctness"
    runs-on: ubuntu-latest
    timeout-minutes: 5
    needs: [install_dependencies]

    steps:
      - uses: actions/checkout@v3
      - uses: ./.github/actions/pnpm
      - name: "App Types"
        run: pnpm run check:types
        working-directory: ${{ env.app }}
      - name: "Monaco configuration Types"
        run: pnpm run check:types
        working-directory: ${{ env.monaco }}
      - name: "Code Mirror configuration Types"
        run: pnpm run check:types
        working-directory: ${{ env.codemirror }}
      - name: "Horizon Types"
        run: pnpm run check:types
        working-directory: ${{ env.horizon }}

