name: "Lints'n'Stuff"
on:
  pull_request:
    branches: [main]

jobs:
  js:
    name: "JS/TS"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install install
    - run: npm run lint:js

  templates:
    name: "Templates"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install install
    - run: npm run lint:hbs

    # - name: "Styles"
    #   run: yarn stylelint ${{ env.app }}/**/*.css

    # - name: "Translations"
    #   run: yarn lint:i18n
    #   continue-on-error: true

  types:
    name: "Type Correctness"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install install
    - run: npm run check:types

