name: "Lints'n'Stuff"
on:
  pull_request:
    branches: [main]

env:
  app: frontend/
  # packages
  codemirror: packages/codemirror/
  consts: packages/consts/
  horizon: packages/horizon-theme/
  monaco: packages/monaco
  sw: packages/transpilation/

jobs:
  js:
    name: "JS/TS"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install
    - name: 'Limber App'
      working-directory: ${{ env.app }}
      run: yarn lint:js
    - name: 'Code Mirror configuration'
      working-directory: ${{ env.codemirror }}
      run: yarn lint:js
    - name: 'Monaco configuration'
      working-directory: ${{ env.monaco }}
      run: yarn lint:js
    - name: 'Consts'
      working-directory: ${{ env.consts }}
      run: yarn lint:js
    - name: 'Horizon Theme'
      working-directory: ${{ env.horizon }}
      run: yarn lint:js
    - name: 'Transpilation'
      working-directory: ${{ env.sw }}
      run: yarn lint:js

  templates:
    name: "Templates"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install
    - run: yarn lint:hbs
      working-directory: ${{ env.app }}

  types:
    name: "Type Correctness"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
    - run: yarn install
    - name: "App Types"
      run: yarn check:types
      working-directory: ${{ env.app }}
    - name: "Monaco configuration Types"
      run: yarn check:types
      working-directory: ${{ env.monaco }}
    - name: "Code Mirror configuration Types"
      run: yarn check:types
      working-directory: ${{ env.codemirror }}
    - name: "Horizon Types"
      run: yarn check:types
      working-directory: ${{ env.horizon }}

