name: "Lints'n'Stuff"
on:
  pull_request:
    branches: [main]

jobs:
  lint:
    name: "Lint JS/TS & Type Checking"
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
    - uses: actions/checkout@v2
    - uses: volta-cli/action@v1
    - uses: actions/cache@v2
      with:
        path: '**/node_modules'
        key: ${{ runner.os }}-modules-${{ hashFiles('**/package-lock.json') }}
    - run: npm install install

    - name: "JS/TS"
      run: npm run lint:js

    - name: "Templates"
      run: num run lint:hbs

    # - name: "Styles"
    #   working-directory: ${{ env.root }}
    #   run: yarn stylelint ${{ env.app }}/**/*.css

    # - name: "Translations"
    #   working-directory: ${{ env.full }}
    #   run: yarn lint:i18n
    #   continue-on-error: true

    # - name: 'Type Correctness'
    #   working-directory: ${{ env.full }}
    #   run: yarn tsc --build

