name: Preview Embroider Upgrade
on:
  schedule:
    # Runs "at minute 0 minutes past midnight" (see https://crontab.guru)
    # - cron: '0 0 * * *'
    - cron: '0/30 * * * *'

env:
  branch: "preview-embroider-upgrade"
  title: "[Unstable] Preview embroider upgrade"
  body: |
    Automated and continuously updated PR (nightly via cron)
    _Do not merge_
  commit: "Update all embroider deps to the unstable version (main)"

jobs:
  update_unstable_branch:
    name: Update Unstable Branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - run: ./dev/update-unstable-embroider.sh
      - uses: peter-evans/create-pull-request@v4
        with:
          # A PAT is required to trigger further workflows
          token: ${{ secrets.GITHUB_TOKEN }}
          commit-message: ${{ env.commit }}
          draft: true
          branch: ${{ env.branch }}
          base: 'main'
          title: ${{ env.title }}
          body: ${{ env.body }}
