name: Preview Embroider Upgrade
on:
  schedule:
    # Runs "at minute 55 past every hour" (see https://crontab.guru)
    - cron: '0 3 * * *'

jobs:
  update_unstable_branch:
    name: Update Unstable Branch
    runs-on: ubuntu-latest
    timeout-minutes: 5

    steps:
      - uses: actions/checkout@v3
      - uses: NullVoxPopuli/action-setup-pnpm@v1.1.0
      - run: ./dev/update-unstable-embroider.sh
